# https://docs.docker.com/compose/overview/
# https://github.com/envygeeks/jekyll-docker/

services:
  site:
    command: jekyll serve --watch --incremental --livereload
    # --verbose
    image: jekyll/jekyll:3.8.6
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
  build:
    command: jekyll build
    image: jekyll/jekyll:3.8.6
    volumes:
      - .:/srv/jekyll
