# https://docs.docker.com/compose/overview/
# https://github.com/envygeeks/jekyll-docker/blob/master/README.md
# https://kristofclaes.github.io/2016/06/19/running-jekyll-locally-with-docker/

services:
  site:
    command: jekyll serve --watch --incremental --livereload
    image: jekyll/jekyll:3.2.1
    # image: jekyll/jekyll:3.9.2
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
  build:
    command: jekyll build
    image: jekyll/jekyll:3.2.1
    # image: jekyll/jekyll:3.9.2
    volumes:
      - .:/srv/jekyll